fire wall

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -127,21 +127,20 @@ jobs:
     - name: Deploy Firewall (iptables)
       run: |
         # Update package information
-        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lxc exec firewall-container -- apt update
+        echo "***" | sudo -S lxc exec firewall-container -- apt update || { echo "Failed to update packages."; cat /etc/apt/sources.list; cat /etc/resolv.conf; exit 1; }
     
         # Check if the iptables rules file exists, and create it if not
         sudo -S lxc exec firewall-container -- mkdir -p /etc/iptables/
-        sudo -S lxc exec firewall-container -- touch /etc/iptables/rules.v4
+        sudo -S lxc exec firewall-container -- touch /etc/iptables/rules.v4 || { echo "Failed to create rules file."; exit 1; }
     
         # Set up iptables rules
-        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lxc exec firewall-container -- iptables -A INPUT -p tcp --dport 22 -j ACCEPT
-        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lxc exec firewall-container -- iptables -A INPUT -p tcp --dport 80 -j ACCEPT
-        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lxc exec firewall-container -- iptables -A INPUT -p tcp --dport 443 -j ACCEPT
-        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lxc exec firewall-container -- iptables -A INPUT -j DROP
+        echo "***" | sudo -S lxc exec firewall-container -- iptables -A INPUT -p tcp --dport 22 -j ACCEPT
+        echo "***" | sudo -S lxc exec firewall-container -- iptables -A INPUT -p tcp --dport 80 -j ACCEPT
+        echo "***" | sudo -S lxc exec firewall-container -- iptables -A INPUT -p tcp --dport 443 -j ACCEPT
+        echo "***" | sudo -S lxc exec firewall-container -- iptables -A INPUT -j DROP
     
         # Save iptables rules to the file
-        echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lxc exec firewall-container -- iptables-save > /etc/iptables/rules.v4
-
+        echo "***" | sudo -S lxc exec firewall-container -- iptables-save > /etc/iptables/rules.v4 || { echo "Failed to save rules to file."; exit 1; }
 
     - name: Get Load Balancer IP
       id: lb_ip
