fatigué

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -33,7 +33,7 @@ jobs:
         if sudo -S lxc info app-container-1 &> /dev/null; then
           echo "Container app-container-1 already exists. Skipping creation."
         else
-          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lxc launch ubuntu:20.04 app-container-1
+          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S lxc launch ubuntu:20.04 app-container-1  || { echo "Failed to launch app-container-1"; exit 1; }
         fi
     
         # Check if app-container-2 exists
